### ISSUE TITLE
Do not remove ID from attributes

### ISSUE THREAD

**Issue by nilportugues** [nilportugues/jsonapi-transformer#65]
While i originally decided to remove it as it is already available as in the standard

After some discussing in https://github.com/nilportugues/laravel5-jsonapi/pull/75#issuecomment-229496366 users asked for to be included as standard says nothing about this, which is true.

**Comment by nilportugues** [comment]
https://github.com/nilportugues/php-json-api/commit/63aa731a45835a96d07cd350f5fd270d876a69a2

**Comment by plattarsu** [comment]
If ID is not removed from attributes, I can't PUT/PATCH data by sending the returned data. I'll need to delete ID from returned data and then send PUT/PATCH request to my api. This is not a big thing to do but it doesn't looks right. If we're following this, is there any way to make request with ID in attributes?
