### ISSUE TITLE
Deeply nested array of objects

### ISSUE THREAD

**Issue by The-Don-Himself** [nilportugues/jsonapi-transformer#86]
Currently travelling but will give proper example when back home on PC.

Basically, post with many comments is ok but post with many comments each with many replies fails.

**Comment by aydot** [comment]
@The-Don-Himself did you figure this out?

**Comment by The-Don-Himself** [comment]
@aydot

Yes, but you will not like the answer. This library fails at complex setups, you will have to use https://github.com/thephpleague/fractal.

It requires more setup and code but it hasnt let me down yet.
